import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { getMovies } from '../actions/movie'
import Form from '../components/Form'
import Header from '../components/Header'
import Movie from '../components/Movie/Movie'
import styles from '../styles/Home.module.css'

export default function Home() {
  const movie = useSelector(state => state.movie.list);
  const dispatch = useDispatch();
  const [movieUpdate, setMovieUpdate] = useState(null);

  useEffect(() => {
    dispatch(getMovies());
  }, [dispatch]);

  const handleUpdate = (movie) => {
    setMovieUpdate(movie);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <div className={styles.content}>
          <div>
            {movie?.length ? movie.map((movie, key) => (
              <Movie key={key} movie={movie} onUpdate={handleUpdate} />
            )) : (
              <p>Không có bộ phim nào</p>
            )}
          </div>

          <Form movie={movieUpdate} />
        </div>

      </main >

      <footer className={styles.footer}>
        Powered by Tùng
      </footer>
    </div >
  )
}
